version: '3.8'

services:
  geoserver:
    image: oscarfonts/geoserver
    container_name: geoserver
    ports:
      - "8080:8080"
    volumes:
      - ./config/geoserver_data:/opt/geoserver/data_dir
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
